version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db
    networks:
      - educativo-network

  config-server:
    build: ./config-server/configserver
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - educativo-network
    depends_on:
      - mongodb

  eureka-server:
    build:
      context: ./eureka-server/eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - educativo-network
    depends_on:
      - config-server

  usuarios-servicio:
    build: ./usuarios-servicio/usuarios-servicio
    container_name: usuarios-servicio
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka-server
      - config-server
      - mongodb
    networks:
      - educativo-network

  asignaturas-servicio:
    build: ./asignaturas-servicio/asignaturas-servicio
    container_name: asignaturas-servicio
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka-server
      - config-server
      - mongodb
    networks:
      - educativo-network

  matriculas-servicio:
    build: ./matriculas-servicio/matriculas-servicio
    container_name: matriculas-servicio
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka-server
      - config-server
      - usuarios-servicio
      - asignaturas-servicio
      - mongodb
    networks:
      - educativo-network

  admin-server:
    build: ./admin-server/admin-server
    container_name: admin-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka-server
      - config-server
    networks:
      - educativo-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - educativo-network
    depends_on:
      - usuarios-servicio
      - asignaturas-servicio
      - matriculas-servicio

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - educativo-network
    depends_on:
      - prometheus

volumes:
  mongodb_data:
  grafana-storage:

networks:
  educativo-network:
    driver: bridge
